Repository adopted-ember-addons/ember-metrics, pull requests merged in 2020-08, with the labels that each got.

#243 Remove usage of deprecated getWithDefault()
  addon/metrics-adapters/google-tag-manager.js
  addon/services/metrics.js
Labels: Type: Refactor

#242 Bump to latest versions (incl. Ember 3.18)
  .editorconfig
  .eslintignore
  .eslintrc.js
  .npmignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  addon/metrics-adapters/facebook-pixel.js
  addon/metrics-adapters/google-analytics.js
  addon/metrics-adapters/google-tag-manager.js
  addon/metrics-adapters/intercom.js
  addon/metrics-adapters/mixpanel.js
  addon/metrics-adapters/piwik.js
  addon/metrics-adapters/segment.js
  addon/services/metrics.js
  config/ember-try.js
  index.js
  package.json
  testem.js
  tests/.eslintrc.js
  tests/acceptance/application-test.js
  tests/dummy/app/app.js
  tests/dummy/app/resolver.js
  tests/dummy/app/router.js
  tests/dummy/app/routes/application.js
  tests/dummy/app/templates/components/.gitkeep
  tests/dummy/config/environment.js
  tests/dummy/config/optional-features.json
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/destroy-app.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/start-app.js
  tests/unit/metrics-adapters/facebook-pixel-test.js
  tests/unit/metrics-adapters/google-analytics-test.js
  tests/unit/metrics-adapters/google-tag-manager-test.js
  tests/unit/metrics-adapters/intercom-test.js
  tests/unit/metrics-adapters/mixpanel-test.js
  tests/unit/metrics-adapters/piwik-test.js
  tests/unit/metrics-adapters/segment-test.js
  tests/unit/services/metrics-test.js
  tests/unit/utils/object-transforms-test.js
  tests/unit/utils/remove-from-dom-test.js
  yarn.lock
Labels: Type: Breaking Change

#224 Update mixpanel adapter tracking code
  addon/metrics-adapters/mixpanel.js
Labels: Type: Enhancement
